---
title: "Lab04"
author: "Bruno José do Nascimento"
date: "5 de fevereiro de 2016"
output: html_document
---

```{r}
library(ggplot2)

```
#geom_point
```{r}

#1-Quais são os aspectos estéticos (aesthetics) exigidos (obrigatórios) da função geom_point()?

ggplot(data = diamonds, aes(x= price, y = carat)) + geom_point()

#2 -  Faça um gráfico de dispersão do preço (price) pela variável quilates (carat). Utilize as funções xlab() e ylab() para trocar os labels dos eixos x e y, respectivamente.

ggplot(data = diamonds, aes(x= carat, y = price)) + geom_point() + xlab("Peso em Quilates") + ylab("Preço (U$)")

# 3. Utilize a facets para fazer gráficos de dispersão do preço pela variável quilate (o mesmo gráfico do exercício 1) para cada nível da variável claridade (clarity).
ggplot(data=diamonds, aes(x=clarity,y=price)) +
  geom_point(aes(colour = cut)) +
  facet_wrap(~cut) +
  labs(x="Peso em Quilates", y= "Preço (U$)", colour = "Corte") + xlab("Claridade") + ylab("Preço em U$")
```

#geom_histogram

```{r}
#4- Quais são os aspectos estéticos (aesthetics) exigidos (obrigatórios) da função geom_histogram()?
ggplot(diamonds, aes(price)) +
  geom_histogram()

#5. Faça um histograma da variável preço. Modifique a cor das barras de forma que elas não pareçam grudadas umas nas outras.
ggplot(diamonds, aes(price)) + 
  geom_histogram(colour = "white", fill = "blue")

#.6. Utilize a função geom_density() para adicionar ao gráfico anterior uma estimativa suavizada da densidade.
ggplot(diamonds, aes(price)) + 
  geom_histogram(colour = "white", fill = "blue") + geom_density()

```

#geom_boxplot

```{r}

#8-  Faça boxplots da variável preço coloridos de acordo com a variável corte (cut).
ggplot(diamonds, aes(x= as.factor(cut), y = price, colour = as.factor(cut))) + geom_boxplot()



ggplot(diamonds, aes(x = as.factor(cut), y = price, fill = as.factor(cut))) + geom_boxplot()

#9 - Substitua as cores padrões e remova a legenda do gráfico anterior. (Dica: use a função scale_color_manual)

```

