---
title: "Lab03"
author: "Bruno José do Nascimento"
date: "22 de janeiro de 2016"
output: html_document
---

```{r}


#Operador pipe %>%
#install.packages("magrittr")
library(magrittr)

#install.packages("nycfligths13")
library(nycflights13)

library(dplyr)



```
##FILTER

```{r}
#1- ATRIBUA A UMA TABELA APENAS OS VOOS DE JANEIRO/2013

flights %>%
  select(year, month, day, dep_time, arr_time, hour, minute)%>%
  filter(year==2013, month == 1)

#2- ATRIBUA A UMA TABELA APENAS OS VOOS DE JANEIRO/2013 e FEV/2013
flights %>%
  select(year, month, day, dep_time, arr_time, hour, minute)%>%
  filter(year==2013, month <= 2)

#3- ATRIBUA A UMA TABELA APENAS OS VOOS COM DISTANCIA MAIOR DO Que 1000 milhas
flights %>%
  select(year, month, day, dep_time, arr_time, hour, minute, distance)%>%
  filter(distance > 1000)

```


##SELECT
```{r}

 #1 - Atribua a uma tabela apenas as colunas month e dep_delay.
  flights %>%
  select(month, dep_delay)

#2 - Atribua a uma tabela apenas as colunas month e dep_delay, os nomes dessas colunas devem ser mes e atraso.
flights %>%
  select(mes = month, atraso =dep_delay)

#3 - Retire da tabela as colunas tailnum, origin e dest
  flights %>%
  select(-tailnum, -origin, -dest)


```

##MUTATE
```{r}

#1- Calcule as colunas ganho_de_tempo que é dado por dep_delay - arr_delay e velocidade dada por distance / air_time * 60.
  flights %>%
  select(air_time, dep_delay, arr_delay, distance, air_time) %>%
  mutate(ganho_de_tempo = dep_delay - arr_delay, velocidade = distance /air_time * 60) %>% tbl_df

#2.Calcule o horário de chegada considerando as colunas hour, minute e air_time. A tabela deve conter duas colunas novas: hour2 com a hora de chegada e minute2 com o minuto de chegada.

flights %>%
  select(year,month, day, hour, minute, air_time) %>%
   mutate(hour2=(((hour*60)+minute +air_time))%/%60, minute2=(((hour*60)+minute +air_time))%%60) %>% tbl_df




```

#SUMMARISE
```{r}

#1. Calcule a média da distância de todos os vôos.
flights %>% summarise(media = mean(distance))

#2. Calcule a média da distância dos vôos por mês
flights %>% group_by(year, month) %>% summarise(media = mean(distance))

#3. Calcule a média, mediana, primeiro quartil e terceiro quartil do tempo de viagem por mês.

flights %>% group_by(year, month) %>% summarise(media = mean(air_time, na.rm = TRUE), mediana = median(air_time, na.rm = TRUE), Primeiro_Quartil = quantile(air_time, 0.25, na.rm = TRUE), Terceiro_Quartil = quantile(air_time, 0.75, na.rm = TRUE))

```

#ARRANGE
```{r}

#1. Ordene a base de dados pelo atraso na partida em ordem crescente
  flights %>% select(year, month, day, dep_time, arr_time, dep_delay) %>%
  arrange((dep_delay)) 

#2. Ordene a base de dados pelo atraso na partida em ordem decrescente
  flights %>% select(year, month, day, dep_time, arr_time, dep_delay) %>%
  arrange(desc(dep_delay)) 

```

#SPREAD

```{r}

#1- Crie uma tabela em que cada linha é um dia e cada coluna é o atraso médio de partida por mês.
library(tidyr)
flights_spread <- flights %>%
  group_by(day, month) %>%
  summarise(atraso=mean(dep_delay, na.rm = TRUE)) %>%
  ungroup()%>%
spread(month, atraso)

flights_spread

#2- Repita a mesma operação, mas dessa vez cada coluna será uma hora do dia
flights %>%
  group_by(hour, day) %>%
  summarise(atraso=mean(dep_delay, na.rm = TRUE)) %>%
  ungroup()%>%
spread(day, atraso)

```

#GATHER

```{r}

#1- Transforme-as em um formato tidy.

flights_spread %>%
  gather(month, atraso, -day ,na.rm=TRUE)


```

